# This is a basic workflow that is manually triggered

name: API docs refresh

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Trigger workflow to update Github pages
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: API docs refresh
          repo: stomp-js/stomp-js.github.io
          ref: master
          token: ${{ secrets.WORKLOW_TOKEN }}
