// 常量
module.exports = {
  // 本地测试
  // IS_DEBUG: true,
  // BASE_HOST: "127.0.0.1:9003",
  // BASE_URL: "http://127.0.0.1:9003",
  // STOMP_WS_URL: "ws://127.0.0.1:9003/stomp",
  // STOMP_SOCKJS_URL: "http://127.0.0.1:9003/sockjs",
  // UPLOAD_FILE_URL: "http://127.0.0.1:9003/visitor/api/v1/upload/file",
  
  // 线上环境
  IS_DEBUG: false,
  BASE_HOST: "api.weiyuai.cn",
  BASE_URL: "https://api.weiyuai.cn",
  STOMP_WS_URL: "wss://api.weiyuai.cn/stomp",
  STOMP_SOCKJS_URL: "https://api.weiyuai.cn/sockjs",
  UPLOAD_FILE_URL: "https://api.weiyuai.cn/visitor/api/v1/upload/file",
  //
  HTTP_CLIENT: 'uniapp',
  PLATFORM: "weiyuai",
  LOCALE: "locale",
  VISITOR_UID: "visitor_uid",
  VISITOR_NICKNAME: "visitor_nickname",
  VISITOR_AVATAR: "visitor_avatar",
  VISITOR_ORGUID: "visitor_orguid",
  VISITOR_DEVICEUID: "visitor_deviceuid",
  I18N_PREFIX: "i18n.",
  // 登录超时
  EVENT_BUS_LOGIN_TIMEOUT: "EVENT_BUS_LOGIN_TIMEOUT",
  // 用户名或密码错误
  EVENT_BUS_LOGIN_ERROR_400: "EVENT_BUS_LOGIN_ERROR_400",
  // 服务器错误500
  EVENT_BUS_SERVER_ERROR_500: "EVENT_BUS_SERVER_ERROR_500",
  // token失效
  EVENT_BUS_TOKEN_INVALID: "EVENT_BUS_TOKEN_INVALID",
  EVENT_BUS_SWITCH_THEME: "EVENT_BUS_SWITCH_THEME",
  //
  EVENT_BUS_MESSAGE_TYPE_STATUS: "EVENT_BUS_MESSAGE_TYPE_STATUS",
  EVENT_BUS_MESSAGE_TYPE_TYPING: "EVENT_BUS_MESSAGE_TYPE_TYPING",
  EVENT_BUS_MESSAGE_TYPE_PROCESSING: "EVENT_BUS_MESSAGE_TYPE_PROCESSING",
  EVENT_BUS_MESSAGE_TYPE_STREAM: "EVENT_BUS_MESSAGE_TYPE_STREAM",
  EVENT_BUS_MESSAGE_TYPE_PREVIEW: "EVENT_BUS_MESSAGE_TYPE_PREVIEW",
  EVENT_BUS_MESSAGE_TYPE_CONTENT: "EVENT_BUS_MESSAGE_TYPE_CONTENT",
  //
  THEME_MODE_TYPE: "THEME_MODE_TYPE",
  THEME_MODE_TYPE_LIGHT: "light",
  THEME_MODE_TYPE_DARK: "dark",
  THEME_MODE_TYPE_SYSTEM: "system",
  //
  THEME_NAME_TYPE: "THEME_NAME_TYPE",
  THEME_NAME_TYPE_DARK: "dark",
  THEME_NAME_TYPE_LIGHT: "light",
  //
  PLAY_AUDIO: "PLAY_AUDIO",
  //
  CONFIG_ENABLED: "CONFIG_ENABLED",
  CONFIG_API_HOST: "CONFIG_API_HOST",
  CONFIG_HTML_HTML: "CONFIG_HTML_HOST",
  //
  USER_TYPE_AGENT: "AGENT",
  USER_TYPE_SYSTEM: "SYSTEM",
  USER_TYPE_VISITOR: "VISITOR",
  USER_TYPE_ROBOT: "ROBOT",
  USER_TYPE_MEMBER: "MEMBER",
  USER_TYPE_ASSISTANT: "ASSISTANT",
  USER_TYPE_CHANNEL: "CHANNEL",
  USER_TYPE_LOCAL: "LOCAL",
  USER_TYPE_USER: "USER",
  //
  // 会话类型:工作组会话、访客跟客服一对一、同事一对一、群组会话
  THREAD_TYPE_AGENT: "AGENT",
  THREAD_TYPE_WORKGROUP: "WORKGROUP",
  THREAD_TYPE_KB: "KB",
  THREAD_TYPE_LLM: "LLM",
  THREAD_TYPE_MEMBER: "MEMBER",
  THREAD_TYPE_GROUP: "GROUP",
  THREAD_TYPE_LEAVEMSG: "LEAVEMSG",
  THREAD_TYPE_FEEDBACK: "FEEDBACK",
  THREAD_TYPE_ASSISTANT: "ASSISTANT",
  THREAD_TYPE_CHANNEL: "CHANNEL",
  THREAD_TYPE_LOCAL: "LOCAL",
  //
  THREAD_STATUS_QUEUING: "QUEUING", // 排队中
  THREAD_STATUS_NORMAL: "NORMAL", // 正常
  THREAD_STATUS_REENTER: "REENTER", // 会话进行中，访客关闭会话页面之后，重新进入
  THREAD_STATUS_REOPEN: "REOPEN", // 会话关闭之后，重新进入
  THREAD_STATUS_OFFLINE: "OFFLINE", // 客服不在线
  THREAD_STATUS_RATED: "RATED", // rated, prevent repeated rate
  THREAD_STATUS_AUTO_CLOSED: "AUTO_CLOSED",
  THREAD_STATUS_AGENT_CLOSED: "AGENT_CLOSED",
  THREAD_STATUS_DISMISSED: "DISMISSED", // 会话解散
  THREAD_STATUS_MUTED: "MUTED", // 会话静音
  THREAD_STATUS_FORBIDDEN: "FORBIDDEN", // 会话禁言
  THREAD_STATUS_MONITORED: "MONITORED", // 会话监控
  // 消息发送状态
  // 发送中
  MESSAGE_STATUS_SENDING: "SENDING", // sending
  MESSAGE_STATUS_TIMEOUT: "TIMEOUT", // network send failed
  MESSAGE_STATUS_BLOCKED: "BLOCKED", // in black list
  MESSAGE_STATUS_NOTFRIEND: "NOTFRIEND", // not friend
  MESSAGE_STATUS_ERROR: "ERROR", // other send error
  MESSAGE_STATUS_SUCCESS: "SUCCESS", // send success
  MESSAGE_STATUS_RECALL: "RECALL", // recall back
  MESSAGE_STATUS_DELIVERED: "DELIVERED", // send to the other client
  MESSAGE_STATUS_READ: "READ", // read by the other client
  MESSAGE_STATUS_DESTROYED: "DESTROYED", // destroyed after read
  MESSAGE_STATUS_UNPRECESSED: "UNPRECESSED", // not processed
  MESSAGE_STATUS_PROCESSED: "PROCESSED", // leave message processed
  MESSAGE_STATUS_LEAVE_MSG_SUBMIT: "LEAVE_MSG_SUBMIT", // 提交留言
  MESSAGE_STATUS_RATE_SUBMIT: "RATE_SUBMIT", // 提交会话评价
  MESSAGE_STATUS_RATE_CANCEL: "RATE_CANCEL", // 取消评价会话
  MESSAGE_STATUS_RATE_UP: "RATE_UP", // 评价消息up
  MESSAGE_STATUS_RATE_DOWN: "RATE_DOWN", // 评价消息down
  //
  // 消息类型
  MESSAGE_TYPE_WELCOME: "WELCOME",
  MESSAGE_TYPE_CONTINUE: "CONTINUE",
  MESSAGE_TYPE_SYSTEM: "SYSTEM",
  MESSAGE_TYPE_TEXT: "TEXT", // 文本消息类型
  MESSAGE_TYPE_IMAGE: "IMAGE", // 图片消息类型
  MESSAGE_TYPE_FILE: "FILE", // 文件消息类型
  MESSAGE_TYPE_AUDIO: "AUDIO", // 语音消息类型
  MESSAGE_TYPE_VIDEO: "VIDEO", // 视频消息类型
  MESSAGE_TYPE_MUSIC: "MUSIC",
  MESSAGE_TYPE_LOCATION: "LOCATION",
  MESSAGE_TYPE_GOODS: "GOODS",
  MESSAGE_TYPE_CARD: "CARD",
  MESSAGE_TYPE_EVENT: "EVENT",
  //
  MESSAGE_TYPE_GUESS: "GUESS", // 猜你想问
  MESSAGE_TYPE_HOT: "HOT", // 热门问题
  MESSAGE_TYPE_SHORTCUT: "SHORTCUT", // 快捷路径
  MESSAGE_TYPE_ORDER: "ORDER", // 订单
  MESSAGE_TYPE_POLL: "POLL", // 投票
  MESSAGE_TYPE_FORM: "FORM", // 表单：询前表单
  MESSAGE_TYPE_LEAVE_MSG: "LEAVE_MSG", // 留言
  MESSAGE_TYPE_LEAVE_MSG_SUBMIT: "LEAVE_MSG_SUBMIT", // 留言提交
  MESSAGE_TYPE_TICKET: "TICKET", // 客服工单
  MESSAGE_TYPE_TYPING: "TYPING", // 正在输入
  MESSAGE_TYPE_PROCESSING: "PROCESSING", // 正在处理，等待大模型回复中
  MESSAGE_TYPE_STREAM: "STREAM", // 流式消息TEXT，大模型回复
  MESSAGE_TYPE_PREVIEW: "PREVIEW", // 消息预知
  MESSAGE_TYPE_RECALL: "RECALL", // 撤回
  MESSAGE_TYPE_DELIVERED: "DELIVERED", // 回执: 已送达
  MESSAGE_TYPE_READ: "READ", // 回执: 已读
  MESSAGE_TYPE_QUOTATION: "QUOTATION", // qoute message
  MESSAGE_TYPE_KICKOFF: "KICKOFF", // kickoff other clients
  MESSAGE_TYPE_SHAKE: "SHAKE", // shake window
  //
  MESSAGE_TYPE_FAQ: "FAQ", // 常见问题FAQ
  MESSAGE_TYPE_FAQ_Q: "FAQ_Q", // 常见问题FAQ-问题
  MESSAGE_TYPE_FAQ_A: "FAQ_A", // 常见问题FAQ-答案
  MESSAGE_TYPE_FAQ_UP: "FAQ_UP", // 常见问题答案评价:UP
  MESSAGE_TYPE_FAQ_DOWN: "FAQ_DOWN", // 常见问题答案评价:DOWN
  MESSAGE_TYPE_ROBOT: "ROBOT", // 机器人
  MESSAGE_TYPE_ROBOT_UP: "ROBOT_UP", // 机器人答案评价:UP
  MESSAGE_TYPE_ROBOT_DOWN: "ROBOT_DOWN", // 机器人答案评价:DOWN
  //
  MESSAGE_TYPE_RATE: "RATE", // 访客主动评价
  MESSAGE_TYPE_RATE_INVITE: "RATE_INVITE", // 客服邀请评价
  MESSAGE_TYPE_RATE_SUBMIT: "RATE_SUBMIT", // 访客提交评价
  MESSAGE_TYPE_RATE_CANCEL: "RATE_CANCEL", // 访客取消评价
  //
  MESSAGE_TYPE_AUTO_CLOSED: "AUTO_CLOSED", // 自动关闭
  MESSAGE_TYPE_AGENT_CLOSED: "AGENT_CLOSED", // 客服关闭
  //
  MESSAGE_TYPE_TRANSFER: "TRANSFER", // 转接
  MESSAGE_TYPE_TRANSFER_ACCEPT: "TRANSFER_ACCEPT", // 转接-接受
  MESSAGE_TYPE_TRANSFER_REJECT: "TRANSFER_REJECT", // 转接-拒绝
  //
  MESSAGE_TYPE_INVITE: "INVITE", // 邀请
  MESSAGE_TYPE_INVITE_ACCEPT: "INVITE_ACCEPT", // 邀请-接受
  MESSAGE_TYPE_INVITE_REJECT: "INVITE_REJECT", // 邀请-拒绝
  //
  TOPIC_FILE_ASSISTANT: "file",
  TOPIC_SYSTEM_NOTIFICATION: "system",
  // 注意：没有 '/' 开头，防止stomp主题中奖 '/' 替换为 '.'之后，在最前面多余一个 '.'
  TOPIC_USER_PREFIX: "user/",
  // TOPIC_PRIVATE_PREFIX:"private/",
  // TOPIC_GROUP_PREFIX:"group/",
  TOPIC_FILE_PREFIX: "file/",
  TOPIC_SYSTEM_PREFIX: "system/",
  // TOPIC_ROBOT_PREFIX:"robot/",
  //
  TOPIC_ORGNIZATION_PREFIX: "org/",
  TOPIC_ORG_MEMBER_PREFIX: "org/member/",
  TOPIC_ORG_DEPARTMENT_PREFIX: "org/department/",
  TOPIC_ORG_GROUP_PREFIX: "org/group/",
  TOPIC_ORG_PRIVATE_PREFIX: "org/private/",
  TOPIC_ORG_ROBOT_PREFIX: "org/robot/",
  TOPIC_ORG_AGENT_PREFIX: "org/agent/",
  TOPIC_ORG_WORKGROUP_PREFIX: "org/workgroup/",
  TOPIC_ORG_KB_PREFIX: "org/kb/",
  TOPIC_ORG_KBDOC_PREFIX: "org/kbdoc/",
  //
  KB_TYPE_ASSISTANT: "ASSISTANT",
  KB_TYPE_HELPDOC: "HELPDOC",
  KB_TYPE_LLM: "LLM",
  KB_TYPE_KEYWORD: "KEYWORD",
  KB_TYPE_FAQ: "FAQ",
  KB_TYPE_QUICKREPLY: "QUICKREPLY",
  KB_TYPE_AUTOREPLY: "AUTOREPLY",
  KB_TYPE_BLOG: "BLOG",
  KB_TYPE_EMAIL: "EMAIL",
  KB_TYPE_TABOO: "TABOO",
  //
  UPLOAD_TYPE_CHAT: "CHAT",
  //
  AUTO_REPLY_TYPE_FIXED: "FIXED",
  AUTO_REPLY_TYPE_KEYWORD: "KEYWORD",
  AUTO_REPLY_TYPE_LLM: "LLM",
  // 
  EVENT_BUS_MESSAGE: 'BYTEDESK_EVENT_BUS_MESSAGE',
  // 连接中
  CONNECTION_STATUS_CONNECTING: 'connecting',
  // 连接成功
  CONNECTION_STATUS_CONNECTED: 'connected',
  // 连接断开
  CONNECTION_STATUS_DISCONNECTED: 'disconnncted',
  // 长连接状态
  EVENT_BUS_CONNECTION_STATUS: 'EVENT_BUS_CONNECTION_STATUS',
}
